### ISSUE TITLE
When field id contains ".", and is an array field, and liveOmit (or omitExtraData) is set to true, then it is not possible to select a value in such field (or submit form).

### ISSUE THREAD

**Issue by OleksiL** [rjsf-team/react-jsonschema-form#2036]
### Prerequisites

- [x ] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

When:
1. field property has "." in its name (not title)
2. that field's type is "array" 
3. omitExtrdaData or liveOmit flags are set to true
Then it is not possible to select a value for such field (if liveOmit is set) or submit the form(if omitExtraData is set) - an error appears "['multiple choices.'] should NOT have fewer than 1 items"

### Steps to Reproduce
1. Go to the playground and paste this schema (layout schema and formData can be left empty)
{
    "type" : "object",
    "required" : [ ],
    "properties" : {
      "multiple choices." : {
        "title" : "multiple choices.",
        "type" : "array",
        "items" : {
          "type" : "string",
          "enum" : [ "opt1", "opt2", "opt3" ],
          "enumNames" : [ "opt1", "opt2", "opt3" ]
        },
        "minItems" : 1,
        "uniqueItems" : true
      }
    }
  }
2. Select liveOmit and omitExtraData options in the playground.
3. Try to select a value on the form.

#### Expected behavior

Value is selected

#### Actual behavior

It is not possible to select the value and error message appears "['multiple choices.'] should NOT have fewer than 1 items"

### Version

1.8.1

**Comment by OleksiL** [comment]
I need it to work because users can enter any field names including dots. And I need omitExtraData option turned on in order to fix a rjsf bug when value from previously selected, but not valid anymore dependency is still sent with the data (e.g. when users selects parent_value1, then child_value1 in dependency, but then changes his mind and selects parent_value2 and child_value2, but for some reason child_value1 is still sent with the data). omitExtraValues solves this issue.

**Comment by adam-beck** [comment]
Here is a working playground link: https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJtdWx0aXBsZSBjaG9pY2VzLiI6WyJvcHQzIl19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbXSwicHJvcGVydGllcyI6eyJtdWx0aXBsZSBjaG9pY2VzLiI6eyJ0aXRsZSI6Im11bHRpcGxlIGNob2ljZXMuIiwidHlwZSI6ImFycmF5IiwiaXRlbXMiOnsidHlwZSI6InN0cmluZyIsImVudW0iOlsib3B0MSIsIm9wdDIiLCJvcHQzIl0sImVudW1OYW1lcyI6WyJvcHQxIiwib3B0MiIsIm9wdDMiXX0sIm1pbkl0ZW1zIjoxLCJ1bmlxdWVJdGVtcyI6dHJ1ZX19fSwidWlTY2hlbWEiOnsiZmlyc3ROYW1lIjp7InVpOmF1dG9mb2N1cyI6dHJ1ZSwidWk6ZW1wdHlWYWx1ZSI6IiIsInVpOmF1dG9jb21wbGV0ZSI6ImZhbWlseS1uYW1lIn0sImxhc3ROYW1lIjp7InVpOmVtcHR5VmFsdWUiOiIiLCJ1aTphdXRvY29tcGxldGUiOiJnaXZlbi1uYW1lIn0sImFnZSI6eyJ1aTp3aWRnZXQiOiJ1cGRvd24iLCJ1aTp0aXRsZSI6IkFnZSBvZiBwZXJzb24iLCJ1aTpkZXNjcmlwdGlvbiI6IihlYXJ0aGlhbiB5ZWFyKSJ9LCJiaW8iOnsidWk6d2lkZ2V0IjoidGV4dGFyZWEifSwicGFzc3dvcmQiOnsidWk6d2lkZ2V0IjoicGFzc3dvcmQiLCJ1aTpoZWxwIjoiSGludDogTWFrZSBpdCBzdHJvbmchIn0sImRhdGUiOnsidWk6d2lkZ2V0IjoiYWx0LWRhdGV0aW1lIn0sInRlbGVwaG9uZSI6eyJ1aTpvcHRpb25zIjp7ImlucHV0VHlwZSI6InRlbCJ9fX0sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjpmYWxzZSwibGl2ZU9taXQiOnRydWV9fQ==

**Comment by adam-beck** [comment]
This seems to be caused by the way `_.pick` works. It does not work when the path contains multiple `.` which would be the case here.

Here is the relevant LOC that returns nothing: https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/core/src/components/Form.js#L186

**Comment by OleksiL** [comment]
By the way, the "." doesn't need to be in the end of field - it can be anywhere in the field id causing the same error.

**Comment by adam-beck** [comment]
Same thing would still apply. `pick` has no way of knowing if the `.` is part of the property name or part of the path:

`some.value`:
- is this a single property named `"some.value"`?
- or is the path `{ some: { value: ... } }`

**Comment by Parro** [comment]
It seems that it's an issue that has been fixed in the main `lodash` package but not in the single `lodash.pick` package, see
https://github.com/lodash/lodash/issues/4459 and https://github.com/lodash/lodash/issues/5005. Importing the full package should solve the issue, but will also increase the bundle size...

**Comment by Parro** [comment]
Ok sorry, I see that we already use the full version of `lodash` 😅

**Comment by epicfaace** [comment]
> Ok sorry, I see that we already use the full version of `lodash` 😅 , I think that this issue can be closed.

Hmm, so is the issue fixed on the latest version of rjsf then?

**Comment by 89erik** [comment]
This is still an issue. I just tried to install the latest version of master, and it still fails.

This also affects objects, as can be seen in [this playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJvYmouMSI6eyJ2YWwiOiJlIn19LCJzY2hlbWEiOnsidHlwZSI6Im9iamVjdCIsInJlcXVpcmVkIjpbIm9iai4xIl0sInByb3BlcnRpZXMiOnsib2JqLjEiOnsidHlwZSI6Im9iamVjdCIsInByb3BlcnRpZXMiOnsidmFsIjp7InR5cGUiOiJzdHJpbmcifX0sInJlcXVpcmVkIjpbInZhbCJdfX19LCJ1aVNjaGVtYSI6e30sInRoZW1lIjoiZGVmYXVsdCIsImxpdmVTZXR0aW5ncyI6eyJ2YWxpZGF0ZSI6ZmFsc2UsImRpc2FibGUiOmZhbHNlLCJvbWl0RXh0cmFEYXRhIjp0cnVlLCJsaXZlT21pdCI6ZmFsc2V9fQ==).

**Comment by 89erik** [comment]
Upgrading lodash to 4.17.20 didn't help.

**Comment by Parro** [comment]
>This is still an issue. I just tried to install the latest version of master, and it still fails.

Yes, the bug is still present, sorry for the confusion. The fix in `lodash` is for searching by properties using dot notation, eg. to search in `{ data: { name: 'name' } }` by `'data.name'`. But searching in an object with dot in the property name, that is our case, is not possible for the way in which `lodash.get` works [lodash/lodash#1637](https://github.com/lodash/lodash/issues/1637). The solution proposed in the issue is to use an array as path 
```_.get({'obj.1': {'val': 'a'}}, ['obj.1', 'val']);```
but I think it would have problems in our case when there are properties in arrays.
