### ISSUE TITLE
Custom Field onChange not working

### ISSUE THREAD

**Issue by LouaiCoolshop** [rjsf-team/react-jsonschema-form#3367]
### Prerequisites

- [X] I have searched the existing issues
- [X] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [X] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/)
- [ ] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

4.2.0

### Current Behavior

In my react app, I have a form with a few fields. Two of them use a custom field. What I'm trying to do is that when the 1st one's value changes, the 2nd one should clear.

To do that, I'm passing all the form's data into the form context, and making the 2nd field check when the 1st field's value changes (using useEffect), and call "onChange(null)".

The problem is that *sometimes* the 2nd field's value doesn't nullify. It would call "onChange(null)" but the "formData" for it does not update, and the field will stay the same.

But, if I put that "onChange(null)" into a setTimeout for 50ms, it works always.

The custom field (simplified):
```ts
function AutoCompleteAsync(props: AutocompleteAsyncFieldProps) { // type extends "FieldProps"
    const {
        id,
        formData,
        onChange,
        customOptions, // [mine] custom options passed
        isDependant, // [mine] custom boolean passed to show if this field depends on another (resets when it changes)
        formContext,
    } = props;

    const [localValue, setLocalValue] = useState<string>('');
    .... other unrelated states ....

    const allFormData = useMemo<Record<string, any>>(
        () => formContext?.allFormData || {},
        [formContext],
    );

    // If this field depends on another field, evaluate the dependance field name and value
    const [dependsOn, dependsOnEntity, dependanceValue] = useMemo<
        [string | null, string | null, string | null]
    >(() => {
        if (isDependant) {
            // "dependsOn" might contain dots (eg "status.key"), so extract "status.key" from allFormData
            const extractedValue: string | null = get(
                allFormData,
                customOptions.asyncData!.dependsOn!,
                null,
            );
            return [
                customOptions.asyncData!.dependsOn!,
                customOptions.asyncData!.dependsOnEntity!,
                extractedValue,
            ];
        }
        return [null, null, null];
    }, [isDependant, customOptions, allFormData]);

    const onValueSelected = useCallback(
        (val: string) => {
                setLocalValue(val);
                onChange(val);
        },
        [onChange],
    );

    useEffect(() => {
        setLocalValue(formData);
    }, [formData]);

    // In case this field depends on another, reset it when the dependent field value changes
    useEffect(() => {
        if (isDependant) {
            // !!! HERE IS THE PROBLEM: setTimeout as workaround to make it work
            setTimeout(() => {
                onChange(null);
            }, 50);
        }
    }, [
        isDependant,
        dependanceValue,
    ]);

    return (
        <Autocomplete
            ...
            value={localValue}
            onChange={(ev, newVal) => {
                setLocalValue(newVal);
                onChange(newVal);
            }}
        />
    );
}

export default AutoCompleteAsync;
```

I'm certain that the "onChange(null)" is being called when I need it. Even used the debugger and stepped in. But sometimes it doesn't update the field formData to null when I don't have that setTimeout.

### Expected Behavior

When I call "onChange(null)", it should always update the formData instead of just sometimes, without needing to use a setTimeout.

### Steps To Reproduce

1. Inside a react app
2. Initialize a form with 2 custom fields
3. Pass in all the form's data into the RJSF component's form context
4. In the second custom field, add a useEffect to the form data's 1st field
5. In that useEffect, call "onChange(null)" when the 1st field's value changes
6. The second field will not update to null sometimes.

### Environment

```markdown
- OS: Windows 11 Pro
- Node: 18.0.0
- npm: 8.6.0
```

**Comment by Stusu** [comment]
I think I have simpler example of the same issue: https://codepen.io/stusu/pen/rNKRmbM
The issue here is that I have 2 custom fields which both calles onChange (from useEffect) at the same time, what causes that the first component does not get new value.
Please check the console for the example I provided, it clearly shows that first component called onChange with new value but it was not passed to it through props.formData

**Comment by heath-freenome** [comment]
@Stusu @LouaiCoolshop The problem here is that the formData is stashed in a state variable on `Form` and the second `onChange()` causes the state to be updated with the original state and not the updated state. Remember react [merges state](https://reactjs.org/docs/state-and-lifecycle.html#state-updates-may-be-asynchronous) in its own time, not immediately. Our code, currently does the bad thing, and not the correct thing (sorry). Do either of you feel comfortable fixing this in the 5.0.0 release?

**Comment by nickgros** [comment]
@balajiram @heath-freenome you may also need to modify `onPropertyClick` in ObjectField.tsx ([link to code](https://github.com/rjsf-team/react-jsonschema-form/blob/e9ec1358b276bb6080de37b5535a7215a5f5a9c3/packages/core/src/components/fields/ObjectField.tsx#L67)).

Ideally, a PR would include a test that uses a simple custom field like in @Stusu 's example to prove that the issue is fixed.

**Comment by heath-freenome** [comment]
@nickgros Since the only place that the state is set is in `Form` I'm not sure `onPropertyChange()` is necessary

**Comment by balajiram** [comment]
@heath-freenome Updating the setState with async syntax on "Form" onChange method didn't fix the change. 

**Reasoning**? (with **[Example 2](https://github.com/rjsf-team/react-jsonschema-form/issues/3367#issuecomment-1378537880)**)
  useEffects starts asynchronously after the component render. So effects have  old state values in their scope(state value before effects start). So the value changed one effect is not available in the scope of the other effect, so form state is not getting updated properly here.

[Example 2](https://github.com/rjsf-team/react-jsonschema-form/issues/3367#issuecomment-1378537880) with updated setState changes [here](https://codesandbox.io/s/loving-hypatia-zxvbhc?file=/src/Form.js). check the console.log statement to assert the reasoning given. 

```
In component updating field1 value yyy -> yyy-changed 
In component updating field2 value zzz -> zzz-changed 

Inside @rjsf/core Form onChange 
oldState field1: yyy field2: zzz 
newState field1: yyy-changed field2: zzz

Inside @rjsf/core Form onChange 
oldState field1: yyy-changed field2: zzz 
newState field1: yyy field2: zzz-changed // here field1 value should be  "yyy-changed" but its "yyy"

Inside @rjsf/core Form onChange 
oldState field1: yyy field2: zzz-changed 
newState field1: yyy-changed field2: zzz

Inside @rjsf/core Form onChange 
oldState field1: yyy-changed field2: zzz 
newState field1: yyy field2: zzz-changed
```

**[Example 1](https://github.com/rjsf-team/react-jsonschema-form/issues/3367#issue-1528521301)** : Updating the state inside the effects is not recommended, check [here](https://beta.reactjs.org/learn/you-might-not-need-an-effect) on more details.  So can you update the logic and try?

**Comment by heath-freenome** [comment]
Ah, as it turns out the issue really is in the `onPropertyChange()` function that @nickgros pointed out. There is no simple fix for this. In fact, it would likely take a reimplementation of how we update formData in containers like objects and arrays. This is no simple feat as it would likely result in a major breaking change. Sorry we don't have an easy fix.

**Comment by psmolaga** [comment]
Hi, everyone! I have discovered that there is a `flushSync` API in React DOM. Perhaps this can help with synchronizing the state updates?

https://react.dev/reference/react-dom/flushSync

**Comment by 0nliner** [comment]
please, fix it T_T

**Comment by 0nliner** [comment]
As a temporary solution, you can store the component's state outside the component. At the beginning of initialization, data is loaded, and then these values are simply passed into the states.

```javascript
let outerComponentState = localStorage.getItem("RJSFOuterState");
const outerSelectedState = outerComponentState ? JSON.parse(outerComponentState)[props.idSchema.$id] : '';
```

**Comment by timkindberg** [comment]
This is quite bad, it's a big architectural flaw, obviously this codebase is old and the pattern was a naive one, so I'm not judging but yeah... this is likely why newer form libraries surgically update using a path, so a nested field would only update it's value within the top-level form data using it's path, e.g. `'foo.bar.baz[0].quux'`. This is likely what we need to happen, so that each field can update in isolation. Right now field updates carry along all of their sibling values in their update and those sibling values might be stale.

**Comment by timkindberg** [comment]
I think I have a potential bandaid. I likely won't make a PR because our codebase is so far behind in version that we use a forked/copied/hacked version of RJSF. But I wanted to share with you guys in case someone wants to do the change and write the tests.

In ObjectField.jsx (this is from v3.2.1, but you should get the idea:

```jsx
onPropertyChange = (name, addedByAdditionalProperties = false) => {
    return (value, errorSchema) => {
      if (value === undefined && addedByAdditionalProperties) {
        // Don't set value = undefined for fields added by
        // additionalProperties. Doing so removes them from the
        // formData, which causes them to completely disappear
        // (including the input field for the property name). Unlike
        // fields which are "mandated" by the schema, these fields can
        // be set to undefined by clicking a "delete field" button, so
        // set empty values to the empty string.
        value = ''
      }

     // HERES THE NEW CODE
      // Add a new tempData thing to accumulate all specific name/value changes that occur before the next render
     // just storing as a ref, so it can exist across calls but doesn't trigger renders
     this.__propertiesChangedSinceLastRender = { ...this.__propertiesChangedSinceLastRender, [name]: value }

// AND SPREAD IT IN HERE
      const newFormData = { ...this.props.formData, ...this.__propertiesChangedSinceLastRender, [name]: value }
      this.props.onChange(
        newFormData,
        errorSchema &&
          this.props.errorSchema && {
            ...this.props.errorSchema,
            [name]: errorSchema
          }
      )
    }
  }

// Then in the render
render() {
  // we can set it back to null here cause we know the state would have "settled" by now
  this.__propertiesChangedSinceLastRender = null
```

**Comment by TheOneTheOnlyJJ** [comment]
I can confirm this is a problem when calling `onChange` on `formContext` changes.

My context is based on parts of the already existing `formData`, and I suspect the `setState` calls are being bundled by React internally, and thus, my 2nd `onChange` call has no effect on the `formData`.

I'm not sure how to get around this cleanly.

**Comment by heath-freenome** [comment]
@TheOneTheOnlyJJ I am putting a fix in this week (finally).
