### ISSUE TITLE
Cannot override <Label>

### ISSUE THREAD

**Issue by awakentwice** [rjsf-team/react-jsonschema-form#408]
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I was trying to make custom TitleField like in [documentation](https://github.com/mozilla-services/react-jsonschema-form#custom-titles) from documentation of custom TitleField

Meanwhile, when I was trying to make custom DescriptionField I've got it.

### Code

```javascript
const Form = JSONSchemaForm.default;
const schema = {
  title: "react-jsonschema-form demo",
  type: "object",
  required: ["name"],
  properties: {
  	name: {type: "string", minLength: 3},
    description: {type: "string"}
  }
};
const uiSchema = {
  description: {
    "ui:widget": "textarea"
  }
};
const CustomTitleField = ({title, required}) => {
  const legend = required ? title + ')(' : title;
  return <div id="custom">{legend}</div>;
};
const fields = {
  TitleField: CustomTitleField
};

ReactDOM.render(<Form schema={schema} uiSchema={uiSchema} fields={fields} />, 
             document.getElementById("main"));
```

### Version
0.41.1

**Comment by n1k0** [comment]
I don't clearly understand what your problem is, but your code works: https://jsfiddle.net/f2y3fq7L/20/

Feel free to reopen if I've missed smthg.

**Comment by elxris** [comment]
Hi! I think it's effectively not working, I've tested on 0.41.1 and the latest version 0.49 and both versions missed to implement the CustomTitleField, notice in the example that instead of '*' he puts a ')('. Or there is something I'm missing?

**Comment by elxris** [comment]
I think this is the problem
https://github.com/mozilla-services/react-jsonschema-form/blob/3df0ab724e31b8742cc43465f699d1b2c9106649/src/components/fields/SchemaField.js#L36-L47
In SchemaField is in use an own implementation of the TitleField instead of the defined one.

**Comment by glasserc** [comment]
Actually, that isn't a `TitleField` but rather a `Label`, and yes, it doesn't seem to be overrideable. Feel free to open a PR if you would like to fix that!

**Comment by elboletaire** [comment]
Related to this... is there any way to properly print HTML in labels? I'm trying to define a label with a link on it and arrived here due to the lack of label customization (but if there's a workaround for my issue, it would do the trick...).

**Comment by elboletaire** [comment]
Oops, sorry, seems there's a more directly related issue to what I was asking (https://github.com/mozilla-services/react-jsonschema-form/issues/687)

**Comment by newt10** [comment]
This should be fixed with FieldTemplate which give control to define your own layout for labels, descriptions, errors and help text.

**Comment by spiderpoul** [comment]
If somebody looking for a solution here some examples: [FieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/FieldTemplate/FieldTemplate.tsx), [ObjectFieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/ObjectFieldTemplate/ObjectFieldTemplate.tsx) and [ArrayFieldTemplate](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/ArrayFieldTemplate/ArrayFieldTemplate.tsx) which allows you to customize labels (through `FieldTemplate`) and group of fields (`ObjectFieldTemplate` or `ArrayFieldTemplate` depending of your form type) and also `FieldTemplate` will add at the top of your form additional wrapper with label, to fix it you need check if field is not addtional - [example](https://github.com/rjsf-team/react-jsonschema-form/blob/master/packages/material-ui/src/FieldTemplate/WrapIfAdditional.tsx#L43)

**Comment by adjenks** [comment]
Shouldn't this allow TextField to be overridden by custom text fields?
https://github.com/rjsf-team/react-jsonschema-form/blob/4be621cc40425cac212a468eff0f8cb14096f82c/packages/material-ui/src/WrapIfAdditionalTemplate/WrapIfAdditionalTemplate.tsx#L63

It still doesn't work as described in the docs since defining the fields prop on Forms doesn't do anything. It would still be nice if you could override this instead of three templates.
