### ISSUE TITLE
Wrong radio button behaviour

### ISSUE THREAD

**Issue by AlimovSV** [rjsf-team/react-jsonschema-form#4634]
### Prerequisites

- [x] I have searched the existing issues
- [x] I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://rjsf-team.github.io/react-jsonschema-form/docs)
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net), [Codesandbox.io](https://codesandbox.io) or preferably a [shared playground link](https://rjsf-team.github.io/react-jsonschema-form/) demonstrating the issue.

### What theme are you using?

core

### Version

5.24.10

### Current Behavior

The radio button `No` is not able to be checked

### Expected Behavior

Radio button `No` should be checkable

### Steps To Reproduce

1. Open [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhIjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6WyJib29sZWFuIiwibnVsbCJdLCJkZWZhdWx0IjpudWxsLCJvbmVPZiI6W3siY29uc3QiOmZhbHNlLCJ0aXRsZSI6Ik5vIn0seyJjb25zdCI6bnVsbCwidGl0bGUiOiJOL0EifV19fSwiYWxsT2YiOlt7ImlmIjp7InJlcXVpcmVkIjpbImEiXSwicHJvcGVydGllcyI6eyJhIjp7ImNvbnN0IjpmYWxzZX19fSwidGhlbiI6eyJyZXF1aXJlZCI6WyJiIl0sInByb3BlcnRpZXMiOnsiYiI6eyJ0eXBlIjoic3RyaW5nIn19fX1dfSwidWlTY2hlbWEiOnsiYSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOmxhYmVsIjpmYWxzZX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJjb25zdEFzRGVmYXVsdHMiOiJhbHdheXMiLCJlbXB0eU9iamVjdEZpZWxkcyI6InBvcHVsYXRlQWxsRGVmYXVsdHMiLCJtZXJnZURlZmF1bHRzSW50b0Zvcm1EYXRhIjoidXNlRm9ybURhdGFJZlByZXNlbnQifX0sInZhbGlkYXRvciI6IkFKVjgiLCJzYW1wbGVOYW1lIjoiQmxhbmsifQ==)
2. Click to `No` button
3. Data is not changed, radio button `No` was not checked

### Environment

```markdown
- OS:
- Node:
- npm:
```

### Anything else?

The same wrong behaviour you can observe if your are using `"ui:widget": "select"` so the original issue is not for radio only.

**Comment by AlimovSV** [comment]
@nickgros Is it possible to publish this fix for 5.x branch?

**Comment by nickgros** [comment]
@AlimovSV Sure. We're not set up in a way that will streamline making new releases to v5, but it shouldn't be too bad. Backport PR is here: https://github.com/rjsf-team/react-jsonschema-form/pull/4654

**Comment by nickgros** [comment]
@AlimovSV We just released [v5.24.11](https://github.com/rjsf-team/react-jsonschema-form/releases/tag/v5.24.11) with the backported changes.

**Comment by AlimovSV** [comment]
@nickgros Thank you very much

**Comment by heath-freenome** [comment]
@AlimovSV I hope it works for you... Otherwise, consider a v6 migration soon?

**Comment by AlimovSV** [comment]
@heath-freenome @nickgros @@abdalla-rko Thank you all very much for your attention to this issue. Unfortunately it doesn't work for me (both v6 and v5). The regression still exists if I use `constAsDefaults: 'never'`. This is [playground](https://rjsf-team.github.io/react-jsonschema-form/#eyJmb3JtRGF0YSI6eyJhIjpudWxsfSwic2NoZW1hIjp7InR5cGUiOiJvYmplY3QiLCJwcm9wZXJ0aWVzIjp7ImEiOnsidHlwZSI6WyJib29sZWFuIiwibnVsbCJdLCJkZWZhdWx0IjpudWxsLCJvbmVPZiI6W3siY29uc3QiOmZhbHNlLCJ0aXRsZSI6Ik5vIn0seyJjb25zdCI6bnVsbCwidGl0bGUiOiJOL0EifV19fSwiYWxsT2YiOlt7ImlmIjp7InJlcXVpcmVkIjpbImEiXSwicHJvcGVydGllcyI6eyJhIjp7ImNvbnN0IjpmYWxzZX19fSwidGhlbiI6eyJyZXF1aXJlZCI6WyJiIl0sInByb3BlcnRpZXMiOnsiYiI6eyJ0eXBlIjoic3RyaW5nIn19fX1dfSwidWlTY2hlbWEiOnsiYSI6eyJ1aTp3aWRnZXQiOiJyYWRpbyIsInVpOmxhYmVsIjpmYWxzZX19LCJ0aGVtZSI6ImRlZmF1bHQiLCJsaXZlU2V0dGluZ3MiOnsic2hvd0Vycm9yTGlzdCI6InRvcCIsInZhbGlkYXRlIjpmYWxzZSwiZGlzYWJsZWQiOmZhbHNlLCJub0h0bWw1VmFsaWRhdGUiOmZhbHNlLCJyZWFkb25seSI6ZmFsc2UsIm9taXRFeHRyYURhdGEiOmZhbHNlLCJsaXZlT21pdCI6ZmFsc2UsImV4cGVyaW1lbnRhbF9kZWZhdWx0Rm9ybVN0YXRlQmVoYXZpb3IiOnsiYXJyYXlNaW5JdGVtcyI6InBvcHVsYXRlIiwiYWxsT2YiOiJza2lwRGVmYXVsdHMiLCJjb25zdEFzRGVmYXVsdHMiOiJuZXZlciIsImVtcHR5T2JqZWN0RmllbGRzIjoicG9wdWxhdGVBbGxEZWZhdWx0cyIsIm1lcmdlRGVmYXVsdHNJbnRvRm9ybURhdGEiOiJ1c2VGb3JtRGF0YUlmUHJlc2VudCJ9fSwidmFsaWRhdG9yIjoiQUpWOCIsInNhbXBsZU5hbWUiOiJCbGFuayJ9) to reproduce this issue.

**Comment by heath-freenome** [comment]
@AlimovSV I tried using the `skipOneOf` and it works. I'm curious why you are trying to use `never`? What is your real use case? Also have you tried playing around with the [emptyObjectFields](https://rjsf-team.github.io/react-jsonschema-form/docs/api-reference/form-props/#emptyobjectfields) prop? If I set it to `skipDefaults` your code also works

**Comment by AlimovSV** [comment]
@heath-freenome Thank you for the response. The simplest scenario is a `Accept terms & condition` checkbox (of course my cases more complex, but I think the scenario is clear). It should be `true`, but should not be checked by default, I want to make a user to click it explicitly (so I use `const: true` for this case). and of course I can't use `skipDefaults` due the rest schema uses some other defaults. Anyway I think that set default values from the schema `const` is not a good practice because `const` is a restriction (validation rule) which should not modify the data. For setting data defaults you need  to use the specific schema modifier - `default` and it looks clear for me. `const` - validation, `default` - modification. So I believe that the example in this issue should work with `never` option. Moreover it was worked before (I used it since 2023 year for RJSF >=4 and <=5.23.1) and some change broke it.

**Comment by NishantChorge7** [comment]
I’m currently using version 6.0.0-beta.10 as I planned to transition to MUI v7. Everything is functioning as it did before, but this issue has now appeared.

**Comment by heath-freenome** [comment]
@AlimovSV @NishantChorge7 Looks like we have another fix coming in beta.11, hold tight

**Comment by AlimovSV** [comment]
@heath-freenome  Is it possible to backport this fix for 5.x branch? Thank you.

**Comment by nickgros** [comment]
@AlimovSV We just released v5.24.12, hopefully this solves the issue for you

**Comment by AlimovSV** [comment]
@nickgros @heath-freenome  Thank you a lot, now all works as expected for me!
